# Generated by Django 4.0.4 on 2022-06-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
