# Generated by Django 4.0.4 on 2022-06-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_carrito_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='producto',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
