# Generated by Django 4.0.4 on 2022-06-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_producto_carrito_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
