# Generated by Django 4.0.4 on 2022-07-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
    ]
