from django.urls import path
from .views import *
urlpatterns = [
    path('', HomeView.as_view(), name='index' ),
    path('carrito/', CarritoDetailView.as_view(), name='carrito' ),
    path('fundacion/', FundacionView.as_view(), name='fundacion' ),
    path('historial/', HistorialView.as_view(), name='historial' ),
    path('login/', login, name='login' ),
    path('perfil/', perfil, name='perfil' ),
    path('register/', register, name='register' ),
    path('registrado/', registrado, name='registrado' ),
    path('detalle_orden/', DetalleOrdenView.as_view(), name='detalle_orden' ),
    path('seguimientovista/', seguimientovista, name='seguimientovista' ),
    path('tienda/<slug>/', TiendaDetailView.as_view(), name='tienda' ),
    path('agregarproducto/', agregarproducto, name='agregarproducto' ),
    path('listarproducto/', listarproducto, name='listarproducto' ),
    path('modificarProducto/<id>', modificarProducto, name='modificarProducto' ),
    path('eliminarproducto/<id>/', eliminarproducto, name='eliminarproducto' ),
    path('registro_usuarios/', registro_usuarios, name='registro_usuarios' ),
    path('agregarusuario/', agregarusuario, name='agregarusuario' ),
    path('listarusuario/', listarusuario, name='listarusuario' ),
    path('modificarusuario/<id>', modificarusuario, name='modificarusuario' ),
    path('eliminarusuario/<id>/', eliminarusuario, name='eliminarusuario' ),
    path('agregar_carrito/<slug>/', agregar_carrito, name='agregar_carrito' ),
    path('borrar_carrito/<slug>/', borrar_carrito, name='borrar_carrito' ),
    path('remover_unidad_producto/<slug>/', remover_unidad_producto, name='remover_unidad_producto' ),
    path('compra_carrito', CompraCarritoView.as_view(), name='compra_carrito' ),
    path('api_digimon/', api_digimon, name='api_digimon'),
    path('comprar_producto/<slug>/', comprar_producto, name='comprar_producto' ),
    path('perfilcrud_users/', perfilcrud_users, name='perfilcrud_users' ),
    path('perfilcrud_productos/', perfilcrud_productos, name='perfilcrud_productos' ),
]